export type SupplementKey =
  | "vitamin-a"
  | "vitamin-b1"
  | "vitamin-b2"
  | "vitamin-b3"
  | "vitamin-b5"
  | "vitamin-b6"
  | "vitamin-b7"
  | "vitamin-b9"
  | "vitamin-b12"
  | "vitamin-b-complex"
  | "vitamin-c"
  | "vitamin-d"
  | "vitamin-d2"
  | "vitamin-e"
  | "vitamin-k"
  | "vitamin-k2"
  | "multivitamin"
  | "iron"
  | "calcium"
  | "magnesium"
  | "magnesium-citrate"
  | "magnesium-malate"
  | "magnesium-threonate"
  | "zinc"
  | "copper"
  | "selenium"
  | "iodine"
  | "chromium"
  | "manganese"
  | "potassium"
  | "boron"
  | "omega-3"
  | "fish-oil"
  | "krill-oil"
  | "algae-oil"
  | "cod-liver-oil"
  | "epa"
  | "dha"
  | "flaxseed-oil"
  | "evening-primrose-oil"
  | "mct-oil"
  | "ashwagandha"
  | "rhodiola"
  | "holy-basil"
  | "maca-root"
  | "ginseng"
  | "eleuthero"
  | "schisandra"
  | "astragalus"
  | "shilajit"
  | "turmeric"
  | "boswellia"
  | "berberine"
  | "lions-mane"
  | "bacopa"
  | "ginkgo"
  | "alpha-gpc"
  | "citicoline"
  | "phosphatidylserine"
  | "huperzine-a"
  | "gaba"
  | "5-htp"
  | "st-johns-wort"
  | "saffron"
  | "lemon-balm"
  | "melatonin"
  | "valerian-root"
  | "passionflower"
  | "probiotics"
  | "prebiotics"
  | "psyllium-husk"
  | "digestive-enzymes"
  | "apple-cider-vinegar"
  | "coq10"
  | "alpha-lipoic-acid"
  | "resveratrol"
  | "quercetin"
  | "nac"
  | "glutathione"
  | "astaxanthin"
  | "collagen"
  | "biotin"
  | "folate"
  | "creatine"
  | "l-glutamine"
  | "l-arginine"
  | "l-citrulline"
  | "l-theanine"
  | "l-tyrosine"
  | "l-tryptophan"
  | "l-carnitine"
  | "acetyl-l-carnitine"
  | "bcaa"
  | "beta-alanine"
  | "glycine"
  | "taurine"
  | "nmn"
  | "nr"
  | "dhea"
  | "spirulina"
  | "chlorella"
  | "moringa"
  | "black-seed-oil"
  | "inositol"
  | "choline"
  | "glucosamine"
  | "chondroitin"
  | "msm"
  | "hyaluronic-acid"
  | "elderberry"
  | "echinacea"
  | "garlic-extract"
  | "saw-palmetto";

export interface SupplementInfo {
  key: SupplementKey;
  displayName: string;
  category:
    | "vitamin"
    | "mineral"
    | "herb"
    | "fatty-acid"
    | "amino-acid"
    | "other";
  color: string;
  bestTime: "morning" | "afternoon" | "evening" | "night";
  withFood: boolean;
  withFoodNote: string;
  timingReason: string;
  pairWith: SupplementKey[];
  pairNote: string;
  avoidWith: SupplementKey[];
  avoidNote: string;
  recommendedDose: string;
}

export const SUPPLEMENT_KNOWLEDGE: Record<SupplementKey, SupplementInfo> = {
  "vitamin-a": {
    key: "vitamin-a",
    displayName: "Vitamin A",
    category: "vitamin",
    color: "#f97316",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "700–900 mcg/day",
    withFoodNote: "Fat-soluble — take with a meal containing healthy fats",
    timingReason: "Morning with breakfast supports daily metabolic activity",
    pairWith: ["vitamin-d", "vitamin-e", "zinc"],
    pairNote: "Zinc helps convert Vitamin A to its active form",
    avoidWith: ["vitamin-k"],
    avoidNote: "High-dose Vitamin A can interfere with Vitamin K activity",
  },
  "vitamin-b1": {
    key: "vitamin-b1",
    displayName: "Vitamin B1 (Thiamine)",
    category: "vitamin",
    color: "#fbbf24",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1.1–1.2 mg/day",
    withFoodNote: "Take with food to maximize absorption",
    timingReason: "Supports carbohydrate metabolism — morning is optimal",
    pairWith: ["vitamin-b-complex", "magnesium"],
    pairNote: "Works best as part of a B-complex",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-b2": {
    key: "vitamin-b2",
    displayName: "Vitamin B2 (Riboflavin)",
    category: "vitamin",
    color: "#fbbf24",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1.1–1.3 mg/day",
    withFoodNote:
      "Take with food — absorption increases significantly with meals",
    timingReason: "Energy metabolism support — morning timing is best",
    pairWith: ["vitamin-b-complex", "vitamin-b6"],
    pairNote: "Works synergistically with other B vitamins",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-b3": {
    key: "vitamin-b3",
    displayName: "Vitamin B3 (Niacin)",
    category: "vitamin",
    color: "#fbbf24",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "14–16 mg/day",
    withFoodNote: "Take with food to reduce flushing",
    timingReason: "Supports NAD+ production and energy throughout the day",
    pairWith: ["vitamin-b-complex", "chromium"],
    pairNote: "Chromium enhances niacin's blood sugar benefits",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-b5": {
    key: "vitamin-b5",
    displayName: "Vitamin B5 (Pantothenic Acid)",
    category: "vitamin",
    color: "#fbbf24",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "5 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Adrenal support and energy metabolism — morning is best",
    pairWith: ["vitamin-b-complex", "vitamin-c"],
    pairNote: "Vitamin C and B5 work together for adrenal health",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-b6": {
    key: "vitamin-b6",
    displayName: "Vitamin B6",
    category: "vitamin",
    color: "#eab308",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1.3–50 mg/day",
    withFoodNote: "Take with food to reduce nausea",
    timingReason:
      "B vitamins support energy metabolism — best taken in the morning",
    pairWith: ["vitamin-b12", "folate", "magnesium"],
    pairNote: "Works synergistically with B12 and folate for methylation",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-b7": {
    key: "vitamin-b7",
    displayName: "Vitamin B7 (Biotin)",
    category: "vitamin",
    color: "#c084fc",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "30–100 mcg/day",
    withFoodNote: "Take with food",
    timingReason: "Supports hair, skin, and nail metabolism throughout the day",
    pairWith: ["zinc", "vitamin-b-complex"],
    pairNote: "Zinc and B-complex enhance biotin's effects",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-b9": {
    key: "vitamin-b9",
    displayName: "Vitamin B9 (Folate)",
    category: "vitamin",
    color: "#4ade80",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "400–800 mcg/day",
    withFoodNote: "Take with food to reduce nausea",
    timingReason: "DNA synthesis support — morning is optimal",
    pairWith: ["vitamin-b12", "vitamin-b6", "vitamin-c"],
    pairNote: "Works in the methylation cycle with B12 and B6",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-b12": {
    key: "vitamin-b12",
    displayName: "Vitamin B12",
    category: "vitamin",
    color: "#a855f7",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "500–1000 mcg/day",
    withFoodNote: "Can be taken with or without food",
    timingReason: "Boosts energy and alertness — avoid taking at night",
    pairWith: ["folate", "vitamin-b6", "vitamin-b-complex"],
    pairNote:
      "Folate and B6 work together with B12 for homocysteine metabolism",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-b-complex": {
    key: "vitamin-b-complex",
    displayName: "Vitamin B Complex",
    category: "vitamin",
    color: "#fbbf24",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1 capsule/day",
    withFoodNote: "Take with breakfast to reduce nausea and boost energy",
    timingReason: "B vitamins drive energy metabolism — never take at night",
    pairWith: ["vitamin-c", "magnesium"],
    pairNote: "Vitamin C enhances B vitamin absorption; magnesium activates B6",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-c": {
    key: "vitamin-c",
    displayName: "Vitamin C",
    category: "vitamin",
    color: "#f97316",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "500–1000 mg/day",
    withFoodNote:
      "Can be taken on empty stomach; take with food if it causes upset",
    timingReason: "Antioxidant protection is best in the morning",
    pairWith: ["iron", "vitamin-e", "collagen"],
    pairNote:
      "Dramatically enhances iron absorption; supports collagen synthesis",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-d": {
    key: "vitamin-d",
    displayName: "Vitamin D3",
    category: "vitamin",
    color: "#facc15",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1000–5000 IU/day",
    withFoodNote: "Fat-soluble — take with a meal containing healthy fats",
    timingReason: "Aligns with natural sunlight-based synthesis rhythm",
    pairWith: ["vitamin-k2", "magnesium", "calcium"],
    pairNote: "K2 directs calcium to bones; magnesium activates Vitamin D",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-d2": {
    key: "vitamin-d2",
    displayName: "Vitamin D2",
    category: "vitamin",
    color: "#fde047",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1000–4000 IU/day",
    withFoodNote: "Fat-soluble — take with a meal containing healthy fats",
    timingReason: "Same as D3 — morning with fat-containing meal",
    pairWith: ["vitamin-k2", "magnesium"],
    pairNote: "K2 and magnesium are essential co-factors",
    avoidWith: [],
    avoidNote: "",
  },
  "vitamin-e": {
    key: "vitamin-e",
    displayName: "Vitamin E",
    category: "vitamin",
    color: "#84cc16",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "15–400 mg/day",
    withFoodNote: "Fat-soluble — take with a meal containing healthy fats",
    timingReason: "Antioxidant — morning intake provides all-day protection",
    pairWith: ["vitamin-c", "selenium"],
    pairNote: "Vitamin C regenerates Vitamin E; selenium acts synergistically",
    avoidWith: ["vitamin-k"],
    avoidNote:
      "High-dose Vitamin E can interfere with Vitamin K clotting activity",
  },
  "vitamin-k": {
    key: "vitamin-k",
    displayName: "Vitamin K1",
    category: "vitamin",
    color: "#22c55e",
    bestTime: "evening",
    withFood: true,
    recommendedDose: "90–120 mcg/day",
    withFoodNote: "Fat-soluble — take with a meal containing healthy fats",
    timingReason:
      "Evening intake supports overnight bone and cardiovascular processes",
    pairWith: ["calcium", "vitamin-d"],
    pairNote: "Works with Vitamin D and calcium for bone health",
    avoidWith: ["vitamin-a", "vitamin-e"],
    avoidNote: "High doses of A or E can reduce Vitamin K effectiveness",
  },
  "vitamin-k2": {
    key: "vitamin-k2",
    displayName: "Vitamin K2 (MK-7)",
    category: "vitamin",
    color: "#10b981",
    bestTime: "evening",
    withFood: true,
    recommendedDose: "90–200 mcg/day",
    withFoodNote: "Fat-soluble — take with dinner",
    timingReason: "Directs calcium to bones during overnight recovery",
    pairWith: ["vitamin-d", "calcium", "magnesium"],
    pairNote:
      "Essential partner to Vitamin D — prevents calcium arterial deposits",
    avoidWith: [],
    avoidNote: "",
  },
  multivitamin: {
    key: "multivitamin",
    displayName: "Multivitamin",
    category: "vitamin",
    color: "#a78bfa",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1 tablet/day",
    withFoodNote: "Take with breakfast for best absorption and to avoid nausea",
    timingReason:
      "Contains fat and water-soluble vitamins — morning with food covers both",
    pairWith: ["omega-3"],
    pairNote:
      "Omega-3 provides fats that help absorb fat-soluble vitamins in the multi",
    avoidWith: ["iron", "calcium", "zinc"],
    avoidNote:
      "If taking standalone iron, calcium, or zinc — separate by 2+ hours",
  },
  iron: {
    key: "iron",
    displayName: "Iron",
    category: "mineral",
    color: "#ef4444",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "8–18 mg/day",
    withFoodNote: "Best absorbed on an empty stomach; take with water or juice",
    timingReason: "Absorption peaks on an empty stomach in the morning",
    pairWith: ["vitamin-c"],
    pairNote: "Vitamin C increases iron absorption by up to 300%",
    avoidWith: ["calcium", "zinc", "magnesium"],
    avoidNote:
      "Calcium, zinc, and magnesium compete with iron — separate by 2+ hours",
  },
  calcium: {
    key: "calcium",
    displayName: "Calcium",
    category: "mineral",
    color: "#94a3b8",
    bestTime: "evening",
    withFood: true,
    recommendedDose: "1000–1200 mg/day",
    withFoodNote: "Take with food for better absorption; split doses if >500mg",
    timingReason:
      "Supports overnight bone remodeling; less competition with other minerals at night",
    pairWith: ["vitamin-d", "vitamin-k2", "magnesium"],
    pairNote: "Vitamin D and K2 ensure calcium goes to bones, not arteries",
    avoidWith: ["iron", "zinc"],
    avoidNote: "Blocks iron and zinc absorption — separate by at least 2 hours",
  },
  magnesium: {
    key: "magnesium",
    displayName: "Magnesium Glycinate",
    category: "mineral",
    color: "#6366f1",
    bestTime: "night",
    withFood: true,
    recommendedDose: "200–400 mg/day",
    withFoodNote: "Take with a light meal or snack to reduce digestive upset",
    timingReason:
      "Promotes muscle relaxation and sleep quality — ideal before bed",
    pairWith: ["vitamin-d", "vitamin-b6", "calcium"],
    pairNote:
      "Required to activate Vitamin D; B6 enhances cellular magnesium uptake",
    avoidWith: ["iron"],
    avoidNote: "Can reduce iron absorption if taken together",
  },
  "magnesium-citrate": {
    key: "magnesium-citrate",
    displayName: "Magnesium Citrate",
    category: "mineral",
    color: "#818cf8",
    bestTime: "night",
    withFood: true,
    recommendedDose: "200–400 mg/day",
    withFoodNote:
      "Take with food — has a mild laxative effect on empty stomach",
    timingReason: "Relaxation and bowel regularity — evening is ideal",
    pairWith: ["vitamin-d", "vitamin-b6"],
    pairNote: "B6 enhances cellular magnesium uptake",
    avoidWith: ["iron"],
    avoidNote: "Can reduce iron absorption if taken together",
  },
  "magnesium-malate": {
    key: "magnesium-malate",
    displayName: "Magnesium Malate",
    category: "mineral",
    color: "#a5b4fc",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "200–400 mg/day",
    withFoodNote: "Take with food",
    timingReason:
      "Malic acid supports energy production — better in the morning than at night",
    pairWith: ["vitamin-d", "vitamin-b-complex"],
    pairNote: "Supports energy metabolism with B vitamins",
    avoidWith: ["iron"],
    avoidNote: "Can reduce iron absorption if taken together",
  },
  "magnesium-threonate": {
    key: "magnesium-threonate",
    displayName: "Magnesium L-Threonate",
    category: "mineral",
    color: "#c7d2fe",
    bestTime: "night",
    withFood: false,
    recommendedDose: "1000–2000 mg/day (144mg elemental)",
    withFoodNote: "Can be taken with or without food",
    timingReason:
      "Crosses the blood-brain barrier — night use supports memory consolidation during sleep",
    pairWith: ["lions-mane", "bacopa"],
    pairNote: "Stacks well with nootropics for cognitive support",
    avoidWith: ["iron"],
    avoidNote: "Can reduce iron absorption if taken together",
  },
  zinc: {
    key: "zinc",
    displayName: "Zinc",
    category: "mineral",
    color: "#3b82f6",
    bestTime: "night",
    withFood: false,
    recommendedDose: "15–30 mg/day",
    withFoodNote: "Best on empty stomach; take with a small snack if nauseous",
    timingReason: "Supports overnight cellular repair and immune function",
    pairWith: ["vitamin-c", "vitamin-a"],
    pairNote: "Vitamin C enhances zinc absorption; zinc activates Vitamin A",
    avoidWith: ["calcium", "iron", "copper"],
    avoidNote: "Competes with calcium, iron, and copper — separate by 2+ hours",
  },
  copper: {
    key: "copper",
    displayName: "Copper",
    category: "mineral",
    color: "#b45309",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1–2 mg/day",
    withFoodNote: "Take with food to reduce nausea",
    timingReason: "Supports morning energy metabolism and iron utilization",
    pairWith: ["vitamin-c", "iron"],
    pairNote: "Required for proper iron metabolism",
    avoidWith: ["zinc"],
    avoidNote: "Zinc and copper compete — high zinc intake depletes copper",
  },
  selenium: {
    key: "selenium",
    displayName: "Selenium",
    category: "mineral",
    color: "#64748b",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "55–200 mcg/day",
    withFoodNote: "Take with food for better absorption",
    timingReason: "Antioxidant — morning intake provides all-day protection",
    pairWith: ["vitamin-e", "vitamin-c"],
    pairNote:
      "Works synergistically with Vitamin E as a powerful antioxidant pair",
    avoidWith: [],
    avoidNote: "",
  },
  iodine: {
    key: "iodine",
    displayName: "Iodine",
    category: "mineral",
    color: "#0891b2",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "150–300 mcg/day",
    withFoodNote: "Can be taken with or without food",
    timingReason:
      "Supports thyroid function — morning aligns with hormone production",
    pairWith: ["selenium"],
    pairNote: "Selenium protects the thyroid during iodine metabolism",
    avoidWith: [],
    avoidNote: "",
  },
  chromium: {
    key: "chromium",
    displayName: "Chromium Picolinate",
    category: "mineral",
    color: "#475569",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "200–1000 mcg/day",
    withFoodNote: "Take with meals to support blood sugar regulation",
    timingReason:
      "Enhances insulin sensitivity — most effective taken with meals",
    pairWith: ["vitamin-b6"],
    pairNote: "Works with B vitamins for glucose metabolism",
    avoidWith: ["calcium"],
    avoidNote: "Calcium carbonate may reduce chromium absorption",
  },
  manganese: {
    key: "manganese",
    displayName: "Manganese",
    category: "mineral",
    color: "#78716c",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1.8–2.3 mg/day",
    withFoodNote: "Take with food",
    timingReason:
      "Supports bone formation and antioxidant activity during the day",
    pairWith: ["calcium", "zinc"],
    pairNote: "Supports bone health alongside calcium",
    avoidWith: ["iron"],
    avoidNote: "Iron can reduce manganese absorption",
  },
  potassium: {
    key: "potassium",
    displayName: "Potassium",
    category: "mineral",
    color: "#f472b6",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "99–3500 mg/day",
    withFoodNote:
      "Always take with food — can cause nausea or stomach upset on empty stomach",
    timingReason:
      "Electrolyte balance — morning supports hydration throughout the day",
    pairWith: ["magnesium"],
    pairNote:
      "Magnesium and potassium work together for heart and muscle function",
    avoidWith: [],
    avoidNote: "",
  },
  boron: {
    key: "boron",
    displayName: "Boron",
    category: "mineral",
    color: "#a16207",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "3–10 mg/day",
    withFoodNote: "Take with food",
    timingReason:
      "Supports testosterone, bone density, and cognitive function during the day",
    pairWith: ["vitamin-d", "magnesium", "vitamin-k2"],
    pairNote: "Enhances the effects of Vitamin D and K2 for bone health",
    avoidWith: [],
    avoidNote: "",
  },
  "omega-3": {
    key: "omega-3",
    displayName: "Omega-3",
    category: "fatty-acid",
    color: "#0ea5e9",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1000–3000 mg/day (EPA+DHA)",
    withFoodNote:
      "Take with a fatty meal for best absorption and to reduce fishy aftertaste",
    timingReason:
      "Morning intake reduces fishy burps and supports all-day anti-inflammatory effects",
    pairWith: ["vitamin-d", "vitamin-e"],
    pairNote:
      "Vitamin E prevents omega-3 oxidation; Vitamin D works synergistically",
    avoidWith: [],
    avoidNote: "",
  },
  "fish-oil": {
    key: "fish-oil",
    displayName: "Fish Oil",
    category: "fatty-acid",
    color: "#0284c7",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1000–3000 mg/day",
    withFoodNote: "Take with a fatty meal to minimize fishy burps",
    timingReason:
      "Morning with food is optimal — reduces fishy aftertaste all day",
    pairWith: ["vitamin-d", "vitamin-e"],
    pairNote: "Vitamin D and E work synergistically with fish oil",
    avoidWith: [],
    avoidNote: "",
  },
  "krill-oil": {
    key: "krill-oil",
    displayName: "Krill Oil",
    category: "fatty-acid",
    color: "#f43f5e",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "500–1000 mg/day",
    withFoodNote: "Take with a meal containing fat",
    timingReason:
      "More bioavailable than fish oil — morning with food is ideal",
    pairWith: ["vitamin-d", "vitamin-e"],
    pairNote: "Synergistic with fat-soluble vitamins",
    avoidWith: [],
    avoidNote: "",
  },
  "algae-oil": {
    key: "algae-oil",
    displayName: "Omega-3 Algae Oil",
    category: "fatty-acid",
    color: "#16a34a",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "250–500 mg DHA/day",
    withFoodNote: "Take with a fatty meal",
    timingReason: "Vegan DHA/EPA source — same timing as fish oil",
    pairWith: ["vitamin-d", "vitamin-e"],
    pairNote: "Fat-soluble vitamins enhance absorption",
    avoidWith: [],
    avoidNote: "",
  },
  "cod-liver-oil": {
    key: "cod-liver-oil",
    displayName: "Cod Liver Oil",
    category: "fatty-acid",
    color: "#0369a1",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1–2 tsp/day",
    withFoodNote: "Take with breakfast",
    timingReason:
      "Contains Vitamins A and D — morning timing is optimal for both",
    pairWith: ["vitamin-k2"],
    pairNote: "K2 balances the Vitamin A and D in cod liver oil",
    avoidWith: ["vitamin-a", "vitamin-d"],
    avoidNote:
      "Avoid additional Vitamin A or D — cod liver oil already contains both",
  },
  epa: {
    key: "epa",
    displayName: "EPA",
    category: "fatty-acid",
    color: "#0ea5e9",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "500–1800 mg/day",
    withFoodNote: "Take with a fatty meal",
    timingReason: "Anti-inflammatory effects are best sustained from morning",
    pairWith: ["dha", "vitamin-e"],
    pairNote: "EPA and DHA work best together",
    avoidWith: [],
    avoidNote: "",
  },
  dha: {
    key: "dha",
    displayName: "DHA",
    category: "fatty-acid",
    color: "#38bdf8",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "200–1000 mg/day",
    withFoodNote: "Take with a fatty meal",
    timingReason:
      "Brain and eye support — morning intake sustains cognitive function all day",
    pairWith: ["epa", "vitamin-e"],
    pairNote: "EPA and DHA work best together",
    avoidWith: [],
    avoidNote: "",
  },
  "flaxseed-oil": {
    key: "flaxseed-oil",
    displayName: "Flaxseed Oil",
    category: "fatty-acid",
    color: "#a3e635",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1–2 tbsp/day",
    withFoodNote: "Take with food — can be added to smoothies or salads",
    timingReason: "ALA omega-3 source — morning with food maximizes absorption",
    pairWith: ["vitamin-e"],
    pairNote: "Vitamin E prevents flaxseed oil oxidation",
    avoidWith: [],
    avoidNote: "",
  },
  "evening-primrose-oil": {
    key: "evening-primrose-oil",
    displayName: "Evening Primrose Oil",
    category: "fatty-acid",
    color: "#f0abfc",
    bestTime: "evening",
    withFood: true,
    recommendedDose: "500–3000 mg/day",
    withFoodNote: "Take with a meal containing fat",
    timingReason: "GLA content supports overnight hormonal balance",
    pairWith: ["vitamin-e", "omega-3"],
    pairNote:
      "Vitamin E prevents oxidation; omega-3 balances the omega-6 content",
    avoidWith: [],
    avoidNote: "",
  },
  "mct-oil": {
    key: "mct-oil",
    displayName: "MCT Oil",
    category: "fatty-acid",
    color: "#fde68a",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "1–3 tbsp/day",
    withFoodNote:
      "Can be taken alone or added to coffee — start with small doses",
    timingReason: "Rapid energy source — morning or pre-workout is ideal",
    pairWith: ["vitamin-d", "omega-3"],
    pairNote: "Enhances absorption of fat-soluble supplements",
    avoidWith: [],
    avoidNote: "",
  },
  ashwagandha: {
    key: "ashwagandha",
    displayName: "Ashwagandha (KSM-66)",
    category: "herb",
    color: "#d97706",
    bestTime: "night",
    withFood: true,
    recommendedDose: "300–600 mg/day",
    withFoodNote: "Take with milk or a light meal to enhance absorption",
    timingReason:
      "Adaptogen that reduces cortisol — night use promotes deep sleep",
    pairWith: ["magnesium", "vitamin-b6"],
    pairNote: "Magnesium and B6 enhance ashwagandha's calming effects",
    avoidWith: [],
    avoidNote: "",
  },
  rhodiola: {
    key: "rhodiola",
    displayName: "Rhodiola Rosea",
    category: "herb",
    color: "#fb923c",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "200–600 mg/day",
    withFoodNote: "Best on empty stomach for faster absorption",
    timingReason: "Stimulating adaptogen — taking at night can disrupt sleep",
    pairWith: ["vitamin-b-complex", "ashwagandha"],
    pairNote:
      "B-complex enhances energy benefits; ashwagandha balances stress response",
    avoidWith: [],
    avoidNote: "",
  },
  "holy-basil": {
    key: "holy-basil",
    displayName: "Holy Basil (Tulsi)",
    category: "herb",
    color: "#4ade80",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "300–600 mg/day",
    withFoodNote: "Take with food",
    timingReason:
      "Adaptogen for stress and blood sugar — morning aligns with cortisol rhythm",
    pairWith: ["ashwagandha"],
    pairNote: "Pairs well with ashwagandha for comprehensive stress support",
    avoidWith: [],
    avoidNote: "",
  },
  "maca-root": {
    key: "maca-root",
    displayName: "Maca Root",
    category: "herb",
    color: "#ca8a04",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1500–3000 mg/day",
    withFoodNote: "Take with food or add to smoothies",
    timingReason:
      "Energy and hormonal support — morning prevents sleep disruption",
    pairWith: ["vitamin-b-complex", "zinc"],
    pairNote: "B vitamins and zinc support maca's hormonal effects",
    avoidWith: [],
    avoidNote: "",
  },
  ginseng: {
    key: "ginseng",
    displayName: "Ginseng",
    category: "herb",
    color: "#dc2626",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "200–400 mg/day",
    withFoodNote: "Best on empty stomach; take with food if it causes upset",
    timingReason: "Stimulating adaptogen — avoid at night to prevent insomnia",
    pairWith: ["vitamin-b-complex"],
    pairNote: "B vitamins enhance ginseng's energy effects",
    avoidWith: [],
    avoidNote: "",
  },
  eleuthero: {
    key: "eleuthero",
    displayName: "Eleuthero",
    category: "herb",
    color: "#b45309",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "300–1200 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Adaptogen for endurance — morning supports all-day stamina",
    pairWith: ["rhodiola", "vitamin-b-complex"],
    pairNote: "Stacks well with rhodiola for athletic performance",
    avoidWith: [],
    avoidNote: "",
  },
  schisandra: {
    key: "schisandra",
    displayName: "Schisandra",
    category: "herb",
    color: "#be123c",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "500–2000 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Liver support and adaptogen — morning is optimal",
    pairWith: ["ashwagandha", "rhodiola"],
    pairNote: "Combines well with other adaptogens",
    avoidWith: [],
    avoidNote: "",
  },
  astragalus: {
    key: "astragalus",
    displayName: "Astragalus",
    category: "herb",
    color: "#fbbf24",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "500–1500 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Immune and longevity support — morning is optimal",
    pairWith: ["vitamin-c", "zinc"],
    pairNote: "Vitamin C and zinc enhance immune effects",
    avoidWith: [],
    avoidNote: "",
  },
  shilajit: {
    key: "shilajit",
    displayName: "Shilajit",
    category: "herb",
    color: "#44403c",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "250–500 mg/day",
    withFoodNote: "Best on empty stomach with warm water or milk",
    timingReason:
      "Boosts testosterone and mitochondrial energy — morning is ideal",
    pairWith: ["zinc", "vitamin-d", "ashwagandha"],
    pairNote:
      "Zinc and Vitamin D amplify shilajit's testosterone-supporting effects",
    avoidWith: [],
    avoidNote: "",
  },
  turmeric: {
    key: "turmeric",
    displayName: "Turmeric / Curcumin",
    category: "herb",
    color: "#f59e0b",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "500–2000 mg/day (curcumin)",
    withFoodNote:
      "Take with a fatty meal and black pepper (piperine) for absorption",
    timingReason: "Anti-inflammatory — morning intake helps throughout the day",
    pairWith: ["omega-3", "vitamin-c"],
    pairNote:
      "Omega-3 and Vitamin C enhance curcumin's anti-inflammatory effects",
    avoidWith: ["iron"],
    avoidNote: "Curcumin can chelate iron — separate by 2+ hours",
  },
  boswellia: {
    key: "boswellia",
    displayName: "Boswellia",
    category: "herb",
    color: "#f97316",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "300–500 mg/day",
    withFoodNote: "Take with food for better absorption",
    timingReason:
      "Anti-inflammatory — morning dosing provides all-day joint relief",
    pairWith: ["turmeric", "omega-3"],
    pairNote: "Powerful anti-inflammatory stack with turmeric and omega-3",
    avoidWith: [],
    avoidNote: "",
  },
  berberine: {
    key: "berberine",
    displayName: "Berberine",
    category: "herb",
    color: "#ca8a04",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "900–1500 mg/day (split doses)",
    withFoodNote: "Take with meals to maximize blood sugar benefits",
    timingReason: "Blood sugar regulation — take before or with meals",
    pairWith: ["chromium", "vitamin-b-complex"],
    pairNote: "Chromium and B vitamins enhance glucose metabolism",
    avoidWith: [],
    avoidNote: "",
  },
  "lions-mane": {
    key: "lions-mane",
    displayName: "Lions Mane Mushroom",
    category: "herb",
    color: "#d4d4d4",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "500–3000 mg/day",
    withFoodNote: "Take with food",
    timingReason:
      "Cognitive enhancer — morning supports focus and productivity all day",
    pairWith: ["bacopa", "alpha-gpc", "magnesium-threonate"],
    pairNote: "Powerful nootropic stack for cognitive enhancement",
    avoidWith: [],
    avoidNote: "",
  },
  bacopa: {
    key: "bacopa",
    displayName: "Bacopa Monnieri",
    category: "herb",
    color: "#86efac",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "300–600 mg/day",
    withFoodNote:
      "Must be taken with food — fat significantly increases absorption",
    timingReason:
      "Memory and cognitive support — consistent morning dosing builds up over weeks",
    pairWith: ["lions-mane", "alpha-gpc"],
    pairNote: "Stacks well with lions mane for comprehensive brain support",
    avoidWith: [],
    avoidNote: "",
  },
  ginkgo: {
    key: "ginkgo",
    displayName: "Ginkgo Biloba",
    category: "herb",
    color: "#bef264",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "120–240 mg/day",
    withFoodNote: "Take with food",
    timingReason:
      "Improves blood flow to the brain — morning supports all-day cognition",
    pairWith: ["bacopa", "lions-mane"],
    pairNote: "Complements other nootropics for memory and focus",
    avoidWith: [],
    avoidNote: "",
  },
  "alpha-gpc": {
    key: "alpha-gpc",
    displayName: "Alpha-GPC",
    category: "other",
    color: "#60a5fa",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "300–600 mg/day",
    withFoodNote: "Can be taken with or without food",
    timingReason:
      "Choline source for acetylcholine — morning supports focus and memory",
    pairWith: ["lions-mane", "bacopa", "citicoline"],
    pairNote:
      "Stacks with other nootropics; avoid combining with citicoline to prevent excess choline",
    avoidWith: ["citicoline"],
    avoidNote:
      "Both are choline sources — taking together may cause too much choline",
  },
  citicoline: {
    key: "citicoline",
    displayName: "Citicoline (CDP-Choline)",
    category: "other",
    color: "#818cf8",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "250–500 mg/day",
    withFoodNote: "Can be taken with or without food",
    timingReason: "Boosts acetylcholine and brain energy — morning is optimal",
    pairWith: ["lions-mane", "bacopa"],
    pairNote: "Powerful nootropic stack",
    avoidWith: ["alpha-gpc"],
    avoidNote:
      "Both are choline sources — avoid combining to prevent excess choline",
  },
  phosphatidylserine: {
    key: "phosphatidylserine",
    displayName: "Phosphatidylserine",
    category: "other",
    color: "#a78bfa",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "100–300 mg/day",
    withFoodNote: "Take with food for best absorption",
    timingReason: "Reduces cortisol and supports memory — morning is optimal",
    pairWith: ["omega-3", "lions-mane"],
    pairNote: "Omega-3 enhances phosphatidylserine's brain health effects",
    avoidWith: [],
    avoidNote: "",
  },
  "huperzine-a": {
    key: "huperzine-a",
    displayName: "Huperzine A",
    category: "herb",
    color: "#c4b5fd",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "50–200 mcg/day",
    withFoodNote: "Can be taken with or without food",
    timingReason:
      "Acetylcholinesterase inhibitor — morning supports all-day cognition",
    pairWith: ["bacopa", "lions-mane"],
    pairNote: "Stacks well with other cognitive enhancers",
    avoidWith: ["alpha-gpc", "citicoline"],
    avoidNote:
      "Combining with high-dose choline sources can cause overstimulation",
  },
  gaba: {
    key: "gaba",
    displayName: "GABA",
    category: "other",
    color: "#7c3aed",
    bestTime: "night",
    withFood: false,
    recommendedDose: "500–750 mg/day",
    withFoodNote: "Best on empty stomach before bed",
    timingReason:
      "Calming neurotransmitter — night use promotes relaxation and sleep",
    pairWith: ["magnesium", "l-theanine"],
    pairNote: "Magnesium and L-theanine enhance GABA's calming effects",
    avoidWith: [],
    avoidNote: "",
  },
  "5-htp": {
    key: "5-htp",
    displayName: "5-HTP",
    category: "other",
    color: "#db2777",
    bestTime: "night",
    withFood: false,
    recommendedDose: "50–300 mg/day",
    withFoodNote: "Best on empty stomach 30-60 min before bed",
    timingReason:
      "Serotonin precursor — night use improves mood and sleep quality",
    pairWith: ["magnesium", "vitamin-b6"],
    pairNote: "B6 is a required cofactor for 5-HTP to convert to serotonin",
    avoidWith: [],
    avoidNote: "",
  },
  "st-johns-wort": {
    key: "st-johns-wort",
    displayName: "St. Johns Wort",
    category: "herb",
    color: "#fbbf24",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "300–900 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Mood support — morning dosing provides all-day benefit",
    pairWith: ["vitamin-d"],
    pairNote: "Vitamin D supports mood alongside St. Johns Wort",
    avoidWith: [],
    avoidNote: "",
  },
  saffron: {
    key: "saffron",
    displayName: "Saffron Extract",
    category: "herb",
    color: "#f59e0b",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "15–30 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Mood and cognitive support — morning is optimal",
    pairWith: ["vitamin-d", "omega-3"],
    pairNote: "Vitamin D and omega-3 support saffron's mood benefits",
    avoidWith: [],
    avoidNote: "",
  },
  "lemon-balm": {
    key: "lemon-balm",
    displayName: "Lemon Balm",
    category: "herb",
    color: "#86efac",
    bestTime: "night",
    withFood: true,
    recommendedDose: "300–600 mg/day",
    withFoodNote: "Can be taken with food or as a tea",
    timingReason: "Calming herb — evening use promotes relaxation and sleep",
    pairWith: ["magnesium", "melatonin"],
    pairNote: "Stacks well with magnesium and melatonin for sleep",
    avoidWith: [],
    avoidNote: "",
  },
  melatonin: {
    key: "melatonin",
    displayName: "Melatonin",
    category: "other",
    color: "#7c3aed",
    bestTime: "night",
    withFood: false,
    recommendedDose: "0.5–5 mg/day",
    withFoodNote: "Take 30-60 minutes before bed on an empty stomach",
    timingReason: "Sleep hormone — only effective when taken close to bedtime",
    pairWith: ["magnesium", "ashwagandha"],
    pairNote: "Magnesium and ashwagandha enhance sleep quality synergistically",
    avoidWith: [],
    avoidNote: "",
  },
  "valerian-root": {
    key: "valerian-root",
    displayName: "Valerian Root",
    category: "herb",
    color: "#8b5cf6",
    bestTime: "night",
    withFood: false,
    recommendedDose: "300–600 mg/day",
    withFoodNote: "Take 30-60 minutes before bed",
    timingReason: "Natural sedative — only take before sleep",
    pairWith: ["magnesium", "melatonin", "lemon-balm"],
    pairNote: "Combines well with magnesium and lemon balm for deep sleep",
    avoidWith: [],
    avoidNote: "",
  },
  passionflower: {
    key: "passionflower",
    displayName: "Passionflower",
    category: "herb",
    color: "#c084fc",
    bestTime: "night",
    withFood: false,
    recommendedDose: "250–500 mg/day",
    withFoodNote: "Take before bed as a tea or capsule",
    timingReason: "Anxiety and sleep support — evening use only",
    pairWith: ["valerian-root", "magnesium"],
    pairNote: "Stacks well with valerian for sleep",
    avoidWith: [],
    avoidNote: "",
  },
  probiotics: {
    key: "probiotics",
    displayName: "Probiotics",
    category: "other",
    color: "#ec4899",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "1–100 billion CFU/day",
    withFoodNote: "Take 30 minutes before a meal on an empty stomach",
    timingReason:
      "Stomach acid is lowest before meals — maximizes bacterial survival",
    pairWith: ["vitamin-d", "omega-3"],
    pairNote: "Vitamin D and Omega-3 support gut microbiome health",
    avoidWith: [],
    avoidNote: "",
  },
  prebiotics: {
    key: "prebiotics",
    displayName: "Prebiotics",
    category: "other",
    color: "#f472b6",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "3–10 g/day",
    withFoodNote: "Take with meals",
    timingReason: "Feeds probiotic bacteria — morning with food is ideal",
    pairWith: ["probiotics"],
    pairNote: "Prebiotics feed probiotics — an essential combination",
    avoidWith: [],
    avoidNote: "",
  },
  "psyllium-husk": {
    key: "psyllium-husk",
    displayName: "Psyllium Husk",
    category: "other",
    color: "#a3e635",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "5–10 g/day",
    withFoodNote: "Take with a full glass of water — never dry",
    timingReason:
      "Fiber for digestion — morning helps establish regular bowel rhythm",
    pairWith: ["probiotics"],
    pairNote: "Acts as a prebiotic feeding probiotic bacteria",
    avoidWith: ["iron", "calcium", "zinc"],
    avoidNote: "Can reduce absorption of minerals — separate by 2+ hours",
  },
  "digestive-enzymes": {
    key: "digestive-enzymes",
    displayName: "Digestive Enzymes",
    category: "other",
    color: "#fde68a",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1–2 capsules per meal",
    withFoodNote: "Take at the very beginning of each meal — not once daily",
    timingReason:
      "Enzymes must be present when food arrives — take with first bites of every meal",
    pairWith: ["probiotics", "l-glutamine"],
    pairNote:
      "Probiotics and glutamine complement enzymes for comprehensive gut health",
    avoidWith: [],
    avoidNote: "",
  },
  "apple-cider-vinegar": {
    key: "apple-cider-vinegar",
    displayName: "Apple Cider Vinegar",
    category: "other",
    color: "#d97706",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "1–2 tbsp diluted in water/day",
    withFoodNote: "Always dilute in water — never take straight",
    timingReason: "Blood sugar and digestion support — before meals is optimal",
    pairWith: ["chromium", "berberine"],
    pairNote: "Stacks with berberine and chromium for blood sugar management",
    avoidWith: [],
    avoidNote: "",
  },
  coq10: {
    key: "coq10",
    displayName: "CoQ10 (Ubiquinol)",
    category: "other",
    color: "#f43f5e",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "100–300 mg/day",
    withFoodNote: "Fat-soluble — take with a fatty meal",
    timingReason: "Supports cellular energy production throughout the day",
    pairWith: ["vitamin-e", "omega-3", "vitamin-b-complex"],
    pairNote:
      "Vitamin E prevents CoQ10 oxidation; B-complex supports energy pathways",
    avoidWith: [],
    avoidNote: "",
  },
  "alpha-lipoic-acid": {
    key: "alpha-lipoic-acid",
    displayName: "Alpha Lipoic Acid",
    category: "other",
    color: "#fbbf24",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "300–600 mg/day",
    withFoodNote: "Best on empty stomach — food reduces absorption by 30%",
    timingReason:
      "Antioxidant and blood sugar support — morning empty stomach is optimal",
    pairWith: ["vitamin-c", "vitamin-e", "coq10"],
    pairNote: "Regenerates vitamins C and E — powerful antioxidant stack",
    avoidWith: ["iron"],
    avoidNote: "Can chelate iron — separate by 2+ hours",
  },
  resveratrol: {
    key: "resveratrol",
    displayName: "Resveratrol",
    category: "other",
    color: "#7f1d1d",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "150–500 mg/day",
    withFoodNote: "Take with a fatty meal for best absorption",
    timingReason: "Longevity and cardiovascular support — morning is optimal",
    pairWith: ["vitamin-c", "quercetin", "omega-3"],
    pairNote: "Quercetin enhances resveratrol's bioavailability and effects",
    avoidWith: [],
    avoidNote: "",
  },
  quercetin: {
    key: "quercetin",
    displayName: "Quercetin",
    category: "other",
    color: "#65a30d",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "500–1000 mg/day",
    withFoodNote: "Take with a fatty meal and bromelain for absorption",
    timingReason: "Anti-inflammatory and immune support — morning is ideal",
    pairWith: ["vitamin-c", "resveratrol", "zinc"],
    pairNote:
      "Vitamin C dramatically increases quercetin absorption; zinc boosts immune effects",
    avoidWith: [],
    avoidNote: "",
  },
  nac: {
    key: "nac",
    displayName: "NAC (N-Acetyl Cysteine)",
    category: "other",
    color: "#2dd4bf",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "600–1800 mg/day",
    withFoodNote: "Best on empty stomach; food can reduce absorption",
    timingReason:
      "Antioxidant and detox support — morning empty stomach maximizes absorption",
    pairWith: ["vitamin-c", "selenium", "vitamin-e"],
    pairNote:
      "Works with Vitamin C and selenium as a powerful antioxidant trio",
    avoidWith: [],
    avoidNote: "",
  },
  glutathione: {
    key: "glutathione",
    displayName: "Glutathione",
    category: "other",
    color: "#34d399",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "250–1000 mg/day",
    withFoodNote: "Best on empty stomach for maximum absorption",
    timingReason: "Master antioxidant — morning empty stomach is optimal",
    pairWith: ["vitamin-c", "nac", "selenium"],
    pairNote: "NAC is a precursor to glutathione; vitamin C regenerates it",
    avoidWith: [],
    avoidNote: "",
  },
  astaxanthin: {
    key: "astaxanthin",
    displayName: "Astaxanthin",
    category: "other",
    color: "#f97316",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "4–12 mg/day",
    withFoodNote: "Fat-soluble — take with a fatty meal",
    timingReason: "Powerful antioxidant — morning provides all-day protection",
    pairWith: ["vitamin-e", "omega-3", "coq10"],
    pairNote: "Synergistic antioxidant stack with vitamin E and CoQ10",
    avoidWith: [],
    avoidNote: "",
  },
  collagen: {
    key: "collagen",
    displayName: "Collagen Peptides",
    category: "other",
    color: "#fb7185",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "5–15 g/day",
    withFoodNote: "Can be added to coffee, smoothie, or taken on empty stomach",
    timingReason: "Morning intake supports all-day collagen synthesis",
    pairWith: ["vitamin-c", "zinc"],
    pairNote:
      "Vitamin C is essential for collagen synthesis — always pair together",
    avoidWith: [],
    avoidNote: "",
  },
  biotin: {
    key: "biotin",
    displayName: "Biotin",
    category: "vitamin",
    color: "#c084fc",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "30–10000 mcg/day",
    withFoodNote: "Take with food to reduce stomach upset",
    timingReason: "B-vitamin — morning supports all-day metabolism",
    pairWith: ["zinc", "vitamin-b-complex"],
    pairNote: "Zinc and B-complex support hair, skin, and nail health together",
    avoidWith: [],
    avoidNote: "",
  },
  folate: {
    key: "folate",
    displayName: "Folate / Folic Acid",
    category: "vitamin",
    color: "#4ade80",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "400–800 mcg/day",
    withFoodNote: "Take with food to reduce nausea",
    timingReason: "DNA synthesis support — morning is optimal",
    pairWith: ["vitamin-b12", "vitamin-b6", "vitamin-c"],
    pairNote: "Works in the methylation cycle with B12 and B6",
    avoidWith: [],
    avoidNote: "",
  },
  creatine: {
    key: "creatine",
    displayName: "Creatine Monohydrate",
    category: "other",
    color: "#38bdf8",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "3–5 g/day",
    withFoodNote: "Can be taken with or without food — mix in water or juice",
    timingReason: "Timing is flexible — consistency matters more than timing",
    pairWith: ["vitamin-d", "magnesium"],
    pairNote:
      "Vitamin D and magnesium support creatine's muscle performance benefits",
    avoidWith: [],
    avoidNote: "",
  },
  "l-glutamine": {
    key: "l-glutamine",
    displayName: "L-Glutamine",
    category: "amino-acid",
    color: "#86efac",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "5–15 g/day",
    withFoodNote: "Best on empty stomach",
    timingReason:
      "Gut repair and recovery — morning on empty stomach is optimal",
    pairWith: ["probiotics", "collagen"],
    pairNote: "Supports gut lining alongside probiotics",
    avoidWith: [],
    avoidNote: "",
  },
  "l-arginine": {
    key: "l-arginine",
    displayName: "L-Arginine",
    category: "amino-acid",
    color: "#f87171",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "3–6 g/day",
    withFoodNote: "Best on empty stomach or pre-workout",
    timingReason: "Nitric oxide booster — morning or pre-workout is ideal",
    pairWith: ["l-citrulline", "vitamin-c"],
    pairNote: "L-citrulline converts to arginine more efficiently in the body",
    avoidWith: [],
    avoidNote: "",
  },
  "l-citrulline": {
    key: "l-citrulline",
    displayName: "L-Citrulline",
    category: "amino-acid",
    color: "#fb923c",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "3–6 g/day",
    withFoodNote: "Best on empty stomach or 30-60 min pre-workout",
    timingReason:
      "More effective than arginine for nitric oxide — pre-workout timing is ideal",
    pairWith: ["l-arginine"],
    pairNote: "Combines with arginine for maximum nitric oxide production",
    avoidWith: [],
    avoidNote: "",
  },
  "l-theanine": {
    key: "l-theanine",
    displayName: "L-Theanine",
    category: "amino-acid",
    color: "#6ee7b7",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "100–400 mg/day",
    withFoodNote: "Can be taken with or without food",
    timingReason: "Promotes calm focus — pairs perfectly with morning coffee",
    pairWith: ["vitamin-b-complex"],
    pairNote: "Pairs with caffeine for calm, focused energy without jitters",
    avoidWith: [],
    avoidNote: "",
  },
  "l-tyrosine": {
    key: "l-tyrosine",
    displayName: "L-Tyrosine",
    category: "amino-acid",
    color: "#fbbf24",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "500–2000 mg/day",
    withFoodNote: "Best on empty stomach — food reduces absorption",
    timingReason:
      "Dopamine precursor for focus and motivation — morning is optimal",
    pairWith: ["vitamin-b6", "vitamin-c"],
    pairNote: "B6 and vitamin C are cofactors for dopamine synthesis",
    avoidWith: [],
    avoidNote: "",
  },
  "l-tryptophan": {
    key: "l-tryptophan",
    displayName: "L-Tryptophan",
    category: "amino-acid",
    color: "#a78bfa",
    bestTime: "night",
    withFood: false,
    recommendedDose: "500–2000 mg/day",
    withFoodNote: "Best on empty stomach before bed",
    timingReason:
      "Serotonin and melatonin precursor — night use supports sleep",
    pairWith: ["vitamin-b6", "magnesium"],
    pairNote:
      "B6 is a required cofactor for tryptophan conversion to serotonin",
    avoidWith: ["5-htp"],
    avoidNote: "Both increase serotonin — avoid combining to prevent excess",
  },
  "l-carnitine": {
    key: "l-carnitine",
    displayName: "L-Carnitine",
    category: "amino-acid",
    color: "#f43f5e",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "500–2000 mg/day",
    withFoodNote: "Take with a carb-containing meal for best uptake",
    timingReason: "Fat metabolism and energy — morning or pre-workout is ideal",
    pairWith: ["coq10", "omega-3"],
    pairNote: "CoQ10 and omega-3 enhance carnitine's fat-burning effects",
    avoidWith: [],
    avoidNote: "",
  },
  "acetyl-l-carnitine": {
    key: "acetyl-l-carnitine",
    displayName: "Acetyl-L-Carnitine",
    category: "amino-acid",
    color: "#fb7185",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "500–1500 mg/day",
    withFoodNote: "Best on empty stomach",
    timingReason:
      "Crosses blood-brain barrier for cognitive and energy support — morning is ideal",
    pairWith: ["alpha-lipoic-acid", "coq10"],
    pairNote: "Powerful mitochondrial support stack with alpha lipoic acid",
    avoidWith: [],
    avoidNote: "",
  },
  bcaa: {
    key: "bcaa",
    displayName: "BCAA",
    category: "amino-acid",
    color: "#38bdf8",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "5–20 g/day",
    withFoodNote: "Take during or around workouts",
    timingReason: "Muscle preservation — take around workout for best results",
    pairWith: ["l-glutamine", "creatine"],
    pairNote: "Stacks with glutamine and creatine for muscle recovery",
    avoidWith: [],
    avoidNote: "",
  },
  "beta-alanine": {
    key: "beta-alanine",
    displayName: "Beta-Alanine",
    category: "amino-acid",
    color: "#f97316",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "2–5 g/day",
    withFoodNote: "Take with food to reduce tingling (paresthesia)",
    timingReason: "Endurance booster — pre-workout or morning is ideal",
    pairWith: ["creatine", "l-citrulline"],
    pairNote: "Classic pre-workout stack with creatine and citrulline",
    avoidWith: [],
    avoidNote: "",
  },
  glycine: {
    key: "glycine",
    displayName: "Glycine",
    category: "amino-acid",
    color: "#a3e635",
    bestTime: "night",
    withFood: false,
    recommendedDose: "3–5 g/day",
    withFoodNote: "Take before bed — can be mixed in water",
    timingReason:
      "Improves sleep quality and lowers core body temperature at night",
    pairWith: ["magnesium", "collagen"],
    pairNote: "Magnesium enhances sleep effects; collagen is rich in glycine",
    avoidWith: [],
    avoidNote: "",
  },
  taurine: {
    key: "taurine",
    displayName: "Taurine",
    category: "amino-acid",
    color: "#67e8f9",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "500–3000 mg/day",
    withFoodNote: "Can be taken with or without food",
    timingReason:
      "Supports heart, muscle, and brain function throughout the day",
    pairWith: ["magnesium", "zinc"],
    pairNote: "Works with magnesium for cardiovascular health",
    avoidWith: [],
    avoidNote: "",
  },
  nmn: {
    key: "nmn",
    displayName: "NMN",
    category: "other",
    color: "#fde68a",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "250–500 mg/day,",
    withFoodNote: "Best on empty stomach in the morning",
    timingReason:
      "Boosts NAD+ levels — morning aligns with circadian NAD+ rhythm",
    pairWith: ["resveratrol", "vitamin-d"],
    pairNote:
      "Resveratrol activates sirtuins that use NAD+ — powerful longevity stack",
    avoidWith: [],
    avoidNote: "",
  },
  nr: {
    key: "nr",
    displayName: "NR (Nicotinamide Riboside)",
    category: "other",
    color: "#fcd34d",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "250–500 mg/day",
    withFoodNote: "Best on empty stomach",
    timingReason: "NAD+ precursor — morning aligns with circadian rhythm",
    pairWith: ["resveratrol", "vitamin-d"],
    pairNote: "Similar to NMN — pairs with resveratrol for longevity",
    avoidWith: ["nmn"],
    avoidNote: "Both boost NAD+ — no need to take both simultaneously",
  },
  dhea: {
    key: "dhea",
    displayName: "DHEA",
    category: "other",
    color: "#f472b6",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "25–50 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Mirrors natural DHEA production which peaks in the morning",
    pairWith: ["vitamin-d", "zinc"],
    pairNote: "Vitamin D and zinc support hormonal balance",
    avoidWith: [],
    avoidNote: "",
  },
  spirulina: {
    key: "spirulina",
    displayName: "Spirulina",
    category: "other",
    color: "#059669",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1–8 g/day",
    withFoodNote: "Take with food or add to smoothies",
    timingReason:
      "Nutrient-dense superfood — morning provides all-day nutritional support",
    pairWith: ["vitamin-c"],
    pairNote: "Vitamin C enhances iron absorption from spirulina",
    avoidWith: [],
    avoidNote: "",
  },
  chlorella: {
    key: "chlorella",
    displayName: "Chlorella",
    category: "other",
    color: "#16a34a",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "3–5 g/day",
    withFoodNote: "Take with food or water",
    timingReason: "Detox and nutrient support — morning is ideal",
    pairWith: ["spirulina", "vitamin-c"],
    pairNote: "Combines well with spirulina as a superfood stack",
    avoidWith: [],
    avoidNote: "",
  },
  moringa: {
    key: "moringa",
    displayName: "Moringa",
    category: "herb",
    color: "#4ade80",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "2–6 g/day",
    withFoodNote: "Take with food or add to smoothies",
    timingReason: "Nutrient-dense and energizing — morning is optimal",
    pairWith: ["vitamin-c", "iron"],
    pairNote: "Vitamin C enhances iron absorption from moringa",
    avoidWith: [],
    avoidNote: "",
  },
  "black-seed-oil": {
    key: "black-seed-oil",
    displayName: "Black Seed Oil",
    category: "other",
    color: "#1c1917",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1–3 tsp/day",
    withFoodNote: "Take with food to reduce stomach irritation",
    timingReason: "Anti-inflammatory and immune support — morning is ideal",
    pairWith: ["omega-3", "vitamin-d"],
    pairNote: "Combines well with omega-3 for anti-inflammatory support",
    avoidWith: [],
    avoidNote: "",
  },
  inositol: {
    key: "inositol",
    displayName: "Inositol",
    category: "other",
    color: "#e879f9",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "500–4000 mg/day",
    withFoodNote: "Can be taken with or without food",
    timingReason: "Supports insulin sensitivity and mood — morning is optimal",
    pairWith: ["vitamin-b-complex", "chromium"],
    pairNote: "B vitamins and chromium enhance inositol's metabolic effects",
    avoidWith: [],
    avoidNote: "",
  },
  choline: {
    key: "choline",
    displayName: "Choline",
    category: "other",
    color: "#60a5fa",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "250–550 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Brain health and liver support — morning is optimal",
    pairWith: ["vitamin-b12", "folate"],
    pairNote: "Works in the methylation cycle with B12 and folate",
    avoidWith: ["alpha-gpc", "citicoline"],
    avoidNote: "Avoid stacking with other choline sources to prevent excess",
  },
  glucosamine: {
    key: "glucosamine",
    displayName: "Glucosamine",
    category: "other",
    color: "#94a3b8",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1500 mg/day",
    withFoodNote: "Take with food to reduce stomach upset",
    timingReason:
      "Joint support — consistent morning dosing builds up over time",
    pairWith: ["chondroitin", "msm", "vitamin-c"],
    pairNote: "Classic joint support trio with chondroitin and MSM",
    avoidWith: [],
    avoidNote: "",
  },
  chondroitin: {
    key: "chondroitin",
    displayName: "Chondroitin",
    category: "other",
    color: "#cbd5e1",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "800–1200 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Joint cartilage support — morning consistency is key",
    pairWith: ["glucosamine", "msm"],
    pairNote: "Works synergistically with glucosamine for joint health",
    avoidWith: [],
    avoidNote: "",
  },
  msm: {
    key: "msm",
    displayName: "MSM",
    category: "other",
    color: "#e2e8f0",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "1500–3000 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Anti-inflammatory for joints and skin — morning is optimal",
    pairWith: ["glucosamine", "chondroitin", "vitamin-c"],
    pairNote: "Vitamin C enhances MSM's collagen synthesis benefits",
    avoidWith: [],
    avoidNote: "",
  },
  "hyaluronic-acid": {
    key: "hyaluronic-acid",
    displayName: "Hyaluronic Acid",
    category: "other",
    color: "#bae6fd",
    bestTime: "morning",
    withFood: false,
    recommendedDose: "80–200 mg/day",
    withFoodNote: "Can be taken with or without food",
    timingReason: "Skin hydration and joint lubrication — morning is ideal",
    pairWith: ["collagen", "vitamin-c"],
    pairNote:
      "Collagen and vitamin C work synergistically with hyaluronic acid",
    avoidWith: [],
    avoidNote: "",
  },
  elderberry: {
    key: "elderberry",
    displayName: "Elderberry",
    category: "herb",
    color: "#7c3aed",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "500–1000 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Immune support — morning dosing provides all-day protection",
    pairWith: ["vitamin-c", "zinc", "echinacea"],
    pairNote: "Stacks well with vitamin C and zinc for immune defense",
    avoidWith: [],
    avoidNote: "",
  },
  echinacea: {
    key: "echinacea",
    displayName: "Echinacea",
    category: "herb",
    color: "#db2777",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "300–500 mg/day",
    withFoodNote: "Take with food",
    timingReason: "Immune stimulant — morning use supports daytime immunity",
    pairWith: ["vitamin-c", "zinc", "elderberry"],
    pairNote: "Combines well with vitamin C and elderberry for immune support",
    avoidWith: [],
    avoidNote: "",
  },
  "garlic-extract": {
    key: "garlic-extract",
    displayName: "Garlic Extract",
    category: "herb",
    color: "#fef9c3",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "600–1200 mg/day",
    withFoodNote: "Always take with food to prevent stomach upset",
    timingReason: "Cardiovascular and immune support — morning is optimal",
    pairWith: ["vitamin-c", "omega-3"],
    pairNote: "Vitamin C and omega-3 enhance garlic's cardiovascular benefits",
    avoidWith: [],
    avoidNote: "",
  },
  "saw-palmetto": {
    key: "saw-palmetto",
    displayName: "Saw Palmetto",
    category: "herb",
    color: "#84cc16",
    bestTime: "morning",
    withFood: true,
    recommendedDose: "160–320 mg/day",
    withFoodNote: "Take with a fatty meal for best absorption",
    timingReason: "Hormonal and prostate support — morning is optimal",
    pairWith: ["zinc", "vitamin-d"],
    pairNote: "Zinc and vitamin D support saw palmetto's hormonal effects",
    avoidWith: [],
    avoidNote: "",
  },
};

// ── Helper functions ──────────────────────────────────────

export function findSupplementByName(name: string): SupplementInfo | null {
  const lower = name.toLowerCase();
  const key = Object.keys(SUPPLEMENT_KNOWLEDGE).find((k) => {
    const info = SUPPLEMENT_KNOWLEDGE[k as SupplementKey];
    return (
      k === lower.replace(/\s+/g, "-") ||
      info.displayName.toLowerCase().includes(lower) ||
      lower.includes(k.replace(/-/g, " "))
    );
  });
  return key ? SUPPLEMENT_KNOWLEDGE[key as SupplementKey] : null;
}

export function getConflicts(
  newKey: SupplementKey,
  existingKeys: SupplementKey[],
): { supplement: SupplementInfo; reason: string }[] {
  const newSupp = SUPPLEMENT_KNOWLEDGE[newKey];
  if (!newSupp) return [];
  return existingKeys
    .filter((k) => newSupp.avoidWith.includes(k))
    .map((k) => ({
      supplement: SUPPLEMENT_KNOWLEDGE[k],
      reason: newSupp.avoidNote,
    }));
}

export function getPairings(
  newKey: SupplementKey,
  existingKeys: SupplementKey[],
): SupplementInfo[] {
  const newSupp = SUPPLEMENT_KNOWLEDGE[newKey];
  if (!newSupp) return [];
  return newSupp.pairWith
    .filter((k) => existingKeys.includes(k))
    .map((k) => SUPPLEMENT_KNOWLEDGE[k]);
}

export const SUPPLEMENT_COLORS = [
  "#facc15",
  "#f97316",
  "#ef4444",
  "#ec4899",
  "#a855f7",
  "#6366f1",
  "#3b82f6",
  "#0ea5e9",
  "#10b981",
  "#84cc16",
];

export function assignColor(index: number): string {
  return SUPPLEMENT_COLORS[index % SUPPLEMENT_COLORS.length];
}
