export const SUPPLEMENT_SUGGESTIONS = [
  // Vitamins
  "Vitamin A",
  "Vitamin B1 (Thiamine)",
  "Vitamin B2 (Riboflavin)",
  "Vitamin B3 (Niacin)",
  "Vitamin B5 (Pantothenic Acid)",
  "Vitamin B6",
  "Vitamin B7 (Biotin)",
  "Vitamin B9 (Folate)",
  "Vitamin B12",
  "Vitamin C",
  "Vitamin D3",
  "Vitamin D2",
  "Vitamin E",
  "Vitamin K1",
  "Vitamin K2 (MK-7)",
  "Vitamin K2 (MK-4)",

  // Minerals
  "Magnesium Citrate",
  "Magnesium Malate",
  "Magnesium L-Threonate",
  "Magnesium Oxide",
  "Calcium Carbonate",
  "Calcium Citrate",
  "Zinc Picolinate",
  "Zinc Gluconate",
  "Zinc Bisglycinate",
  "Iron Bisglycinate",
  "Iron Sulfate",
  "Iodine",
  "Selenium",
  "Chromium Picolinate",
  "Manganese",
  "Copper",
  "Potassium",
  "Boron",
  "Molybdenum",
  "Vanadium",
  "Silica",

  // Omega / Fatty Acids
  "Omega-3 Fish Oil",
  "Omega-3 Algae Oil",
  "Krill Oil",
  "EPA",
  "DHA",
  "Flaxseed Oil",
  "Evening Primrose Oil",
  "MCT Oil",

  // Amino Acids
  "L-Glutamine",
  "L-Arginine",
  "L-Citrulline",
  "L-Theanine",
  "L-Tyrosine",
  "L-Tryptophan",
  "L-Carnitine",
  "Acetyl-L-Carnitine",
  "BCAA",
  "Leucine",
  "Lysine",
  "Glycine",
  "Taurine",
  "Beta-Alanine",

  // Performance & Fitness
  "Creatine Monohydrate",
  "Creatine HCL",
  "Pre-Workout",
  "Whey Protein",
  "Casein Protein",
  "Plant Protein",
  "Collagen Peptides",
  "Collagen Type I",
  "Collagen Type II",
  "HMB",
  "Beta-Ecdysterone",

  // Adaptogens & Herbs
  "Ashwagandha (KSM-66)",
  "Ashwagandha (Sensoril)",
  "Rhodiola Rosea",
  "Holy Basil (Tulsi)",
  "Maca Root",
  "Ginseng",
  "Eleuthero",
  "Schisandra",
  "Astragalus",
  "Shilajit",

  // Brain & Mood
  "Lions Mane Mushroom",
  "Bacopa Monnieri",
  "Ginkgo Biloba",
  "Alpha-GPC",
  "Citicoline (CDP-Choline)",
  "Phosphatidylserine",
  "Huperzine A",
  "GABA",
  "5-HTP",
  "St. Johns Wort",
  "Saffron Extract",
  "Lemon Balm",

  // Gut & Digestion
  "Probiotics",
  "Lactobacillus Acidophilus",
  "Bifidobacterium",
  "Prebiotics",
  "Psyllium Husk",
  "Digestive Enzymes",
  "Apple Cider Vinegar",
  "Betaine HCL",
  "Glutamine",
  "Aloe Vera",

  // Antioxidants & Anti-inflammatory
  "CoQ10 (Ubiquinol)",
  "CoQ10 (Ubiquinone)",
  "Alpha Lipoic Acid",
  "Resveratrol",
  "Quercetin",
  "NAC (N-Acetyl Cysteine)",
  "Glutathione",
  "Astaxanthin",
  "Lutein",
  "Zeaxanthin",
  "Turmeric (Curcumin)",
  "Boswellia",
  "Berberine",

  // Sleep
  "Melatonin",
  "Magnesium Glycinate",
  "Apigenin",
  "Valerian Root",
  "Passionflower",
  "Chamomile Extract",

  // Immune
  "Zinc",
  "Vitamin C",
  "Elderberry",
  "Echinacea",
  "Andrographis",
  "Garlic Extract",
  "Oregano Oil",

  // Hormones & Longevity
  "DHEA",
  "Pregnenolone",
  "NMN",
  "NR (Nicotinamide Riboside)",
  "Fisetin",
  "Spermidine",
  "Metformin",
  "Rapamycin",

  // Skin, Hair & Nails
  "Biotin",
  "Collagen",
  "Hyaluronic Acid",
  "Silica",
  "MSM",
  "Keratin",
  "Saw Palmetto",
  "Pumpkin Seed Oil",

  // Bone & Joint
  "Glucosamine",
  "Chondroitin",
  "MSM",
  "Vitamin D3 + K2",
  "Calcium + Magnesium",
  "Strontium",

  // Misc
  "Spirulina",
  "Chlorella",
  "Wheatgrass",
  "Moringa",
  "Black Seed Oil",
  "Cod Liver Oil",
  "Liver Supplements",
  "Inositol",
  "Choline",
  "Lithium Orotate",
];
